name: CI pipeline for main branch

on:
  push:
    branches:
      - main

jobs:
  ci-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.6

      - name: install node_modules
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build